name: "Assert Branch Naming Convention"
on: pull_request

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: imitsuo/action-branch-name@master
        with:
          regex: "^(feature|feat|fix|stable)(-|_)([a-z]|[0-9])+((-|_)([a-z]|[0-9])+)+" # Regex the branch should match. This example enforces grouping
          allowed_prefixes: "feat,feature,stable,fix" # All branches should start with the given prefix
          ignore: main,master,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 50 # Max length of the branch name
